id: D56AE5666
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T11:06:31+00:00'
last_modified: '2022-05-30T07:39:30.965008+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    bb3b:
      image_group_id: I1PD95892
      title: ཁྲོ་བོ་རེག་ཚིག་གི་དམ་ཚིག་གསང་བའི་བསྒྲུབ་ཐབས།
      total_pages: 1464
      order: 47
      base_file: bb3b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
